const symbolGroups = [

    // ['BTCUSDT_PERP.A']
['ZRXUSDT_PERP.A, COMPUSDT_PERP.A, DOGEUSDT_PERP.A, KAVAUSDT_PERP.A, BANDUSDT_PERP.A, RLCUSDT_PERP.A, SNXUSDT_PERP.A, DOTUSDT_PERP.A, YFIUSDT_PERP.A, CRVUSDT_PERP.A, TRBUSDT_PERP.A, RUNEUSDT_PERP.A, SUSHIUSDT_PERP.A, EGLDUSDT_PERP.A, SOLUSDT_PERP.A, ICXUSDT_PERP.A, STORJUSDT_PERP.A, UNIUSDT_PERP.A, AVAXUSDT_PERP.A, ENJUSDT_PERP.A'],
['KSMUSDT_PERP.A, NEARUSDT_PERP.A, AAVEUSDT_PERP.A, FILUSDT_PERP.A, RSRUSDT_PERP.A, BELUSDT_PERP.A, AXSUSDT_PERP.A, ZENUSDT_PERP.A, SKLUSDT_PERP.A, GRTUSDT_PERP.A, 1INCHUSDT_PERP.A, CHZUSDT_PERP.A, SANDUSDT_PERP.A, ANKRUSDT_PERP.A, RVNUSDT_PERP.A, SFPUSDT_PERP.A, COTIUSDT_PERP.A, CHRUSDT_PERP.A, MANAUSDT_PERP.A, ALICEUSDT_PERP.A'],
['HBARUSDT_PERP.A, ONEUSDT_PERP.A, CELRUSDT_PERP.A, HOTUSDT_PERP.A, MTLUSDT_PERP.A, OGNUSDT_PERP.A, 1000SHIBUSDT_PERP.A, GTCUSDT_PERP.A, BTCDOMUSDT_PERP.A, IOTXUSDT_PERP.A, C98USDT_PERP.A, MASKUSDT_PERP.A, DYDXUSDT_PERP.A, 1000XECUSDT_PERP.A, GALAUSDT_PERP.A, CELOUSDT_PERP.A, ARUSDT_PERP.A, ARPAUSDT_PERP.A, CTSIUSDT_PERP.A, LPTUSDT_PERP.A'],
['ENSUSDT_PERP.A, PEOPLEUSDT_PERP.A, ROSEUSDT_PERP.A, DUSKUSDT_PERP.A, FLOWUSDT_PERP.A, IMXUSDT_PERP.A, API3USDT_PERP.A, GMTUSDT_PERP.A, APEUSDT_PERP.A, WOOUSDT_PERP.A, JASMYUSDT_PERP.A, OPUSDT_PERP.A, INJUSDT_PERP.A, STGUSDT_PERP.A, SPELLUSDT_PERP.A, 1000LUNCUSDT_PERP.A, LUNA2USDT_PERP.A, LDOUSDT_PERP.A, ICPUSDT_PERP.A, APTUSDT_PERP.A'],
['QNTUSDT_PERP.A, FETUSDT_PERP.A, MAGICUSDT_PERP.A, TUSDT_PERP.A, MINAUSDT_PERP.A, ASTRUSDT_PERP.A, GMXUSDT_PERP.A, CFXUSDT_PERP.A, STXUSDT_PERP.A, ACHUSDT_PERP.A, SSVUSDT_PERP.A, CKBUSDT_PERP.A, LQTYUSDT_PERP.A, USDCUSDT_PERP.A, IDUSDT_PERP.A, ARBUSDT_PERP.A, JOEUSDT_PERP.A, TLMUSDT_PERP.A, XVSUSDT_PERP.A, BLURUSDT_PERP.A'],

];





module.exports = symbolGroups;

