const symbolGroups = [
['MAGICUSDT_PERP.A,ILVUSDT_PERP.A,ALICEUSDT_PERP.A,HOOKUSDT_PERP.A,IDUSDT_PERP.A,ARKUSDT_PERP.A,CTSIUSDT_PERP.A,CELRUSDT_PERP.A,COTIUSDT_PERP.A,KAVAUSDT_PERP.A,MINAUSDT_PERP.A,ROSEUSDT_PERP.A,ONEUSDT_PERP.A,IOTXUSDT_PERP.A,ZILUSDT_PERP.A,DUSKUSDT_PERP.A,RSRUSDT_PERP.A,SKLUSDT_PERP.A,ANKRUSDT_PERP.A,API3USDT_PERP.A'],
['LRCUSDT_PERP.A,HOTUSDT_PERP.A,CHRUSDT_PERP.A,OGNUSDT_PERP.A,MTLUSDT_PERP.A,SXPUSDT_PERP.A,ICXUSDT_PERP.A,ONTUSDT_PERP.A,WAVESUSDT_PERP.A,ZENUSDT_PERP.A,QTUMUSDT_PERP.A,DASHUSDT_PERP.A,ZECUSDT_PERP.A,RVNUSDT_PERP.A,KSMUSDT_PERP.A,ARUSDT_PERP.A,GMXUSDT_PERP.A,CFXUSDT_PERP.A,FLOWUSDT_PERP.A,EGLDUSDT_PERP.A'],
['HBARUSDT_PERP.A,KLAYUSDT_PERP.A,FTMUSDT_PERP.A,ASTRUSDT_PERP.A,GLMRUSDT_PERP.A,CELOUSDT_PERP.A,SCUSDT_PERP.A,STORJUSDT_PERP.A,AUDIOUSDT_PERP.A,PEOPLEUSDT_PERP.A,JOEUSDT_PERP.A,TWTUSDT_PERP.A,XVSUSDT_PERP.A,EDUUSDT_PERP.A,SSVUSDT_PERP.A,TRBUSDT_PERP.A,WOOUSDT_PERP.A,BANDUSDT_PERP.A,RLCUSDT_PERP.A,UMAUSDT_PERP.A'],
['LITUSDT_PERP.A,BICOUSDT_PERP.A,MDTUSDT_PERP.A,NKNUSDT_PERP.A,FLMUSDT_PERP.A,KEYUSDT_PERP.A,RADUSDT_PERP.A,HIFIUSDT_PERP.A,COMBOUSDT_PERP.A,AMBUSDT_PERP.A,BLZUSDT_PERP.A,ATAUSDT_PERP.A,DARUSDT_PERP.A,DENTUSDT_PERP.A,OCEANUSDT_PERP.A,NMRUSDT_PERP.A,KNCUSDT_PERP.A,PHAUSDT_PERP.A,CTKUSDT_PERP.A,STGUSDT_PERP.A'],
['IDEXUSDT_PERP.A,XVGUSDT_PERP.A,RENUSDT_PERP.A,REEFUSDT_PERP.A,TLMUSDT_PERP.A,BAKEUSDT_PERP.A,ALPHAUSDT_PERP.A,LEVERUSDT_PERP.A,SPELLUSDT_PERP.A,LINAUSDT_PERP.A,PERPUSDT_PERP.A,ACHUSDT_PERP.A,SLPUSDT_PERP.A,STMXUSDT_PERP.A,COCOSUSDT_PERP.A,DODOUSDT_PERP.A,AERGOUSDT_PERP.A,ARPAUSDT_PERP.A,C98USDT_PERP.A,AGLDUSDT_PERP.A'],

];





module.exports = symbolGroups;

